class OmniSpanAttributes:
    REQUEST_ID = "vllm_omni.request.id"
    REQUEST_NUM_STAGES = "vllm_omni.request.num_stages"
    ENGINE_IDX = "vllm_omni.engine.idx"
    STAGE_ID = "vllm_omni.stage.id"
    STAGE_NAME = "vllm_omni.stage.name"
    STAGE_MODEL = "vllm_omni.stage.model"
    STAGE_REPLICA_ID = "vllm_omni.stage.replica_id"
    LATENCY_INTER_STAGE_QUEUE = "vllm_omni.latency.inter_stage_queue"
    LATENCY_STAGE_TOTAL = "vllm_omni.latency.stage_total"
    PIPELINE_TIMINGS = "vllm_omni.pipeline.timings"
    CONNECTOR_TYPE = "vllm_omni.connector.type"
    OUTPUT_MODALITY = "vllm_omni.output.modality"
    DIFFUSION_PREPROCESS_MS = "vllm_omni.diffusion.preprocess_ms"
    DIFFUSION_EXEC_MS = "vllm_omni.diffusion.exec_ms"
    DIFFUSION_POSTPROCESS_MS = "vllm_omni.diffusion.postprocess_ms"
    DIFFUSION_TOTAL_MS = "vllm_omni.diffusion.total_ms"
