apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omni-demo

resources:
  - 00-servingruntime.yaml
  - 01-inferenceservice.yaml
  - 02-prometheus-configmap.yaml
  - 03-referencegrant.yaml
  - 04-httproute.yaml
  - 05-gateway-service.yaml

# Common labels to add to all resources
labels:
  - pairs:
      app.kubernetes.io/name: vllm-omni
      app.kubernetes.io/component: inference
