---
apiVersion: v1
kind: Secret
metadata:
  name: keda-prometheus-token
  namespace: omni-demo
  annotations:
    kubernetes.io/service-account.name: keda-prometheus-sa
type: kubernetes.io/service-account-token
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
  namespace: omni-demo
spec:
  secretTargetRef:
  - parameter: bearerToken
    name: keda-prometheus-token
    key: token
  - parameter: ca
    name: keda-prometheus-token
    key: ca.crt
