apiVersion: v1
kind: ServiceAccount
metadata:
  name: keda-prometheus-sa
  namespace: omni-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keda-prometheus-metrics-reader
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-prometheus-metrics-reader-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: keda-prometheus-metrics-reader
subjects:
- kind: ServiceAccount
  name: keda-prometheus-sa
  namespace: omni-demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: keda-prometheus-monitoring-view
subjects:
- kind: ServiceAccount
  name: keda-prometheus-sa
  namespace: omni-demo
roleRef:
  kind: ClusterRole
  name: cluster-monitoring-view
  apiGroup: rbac.authorization.k8s.io
