apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: omni-demo

resources:
  - omni-servingruntime.yaml
  - omni-inferenceservice.yaml
  - omni-route.yaml
  - prom-configmap.yaml

# Common labels to add to all resources
labels:
  - pairs:
      app.kubernetes.io/name: vllm-omni
      app.kubernetes.io/component: inference
